// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnzHHUS-J5nYG-czs1xdJhUaKJ-HYvQ7I',
    appId: '1:83204591815:web:d2ac2b9275e59a6f1caee2',
    messagingSenderId: '83204591815',
    projectId: 'ecofund-c4310',
    authDomain: 'ecofund-c4310.firebaseapp.com',
    storageBucket: 'ecofund-c4310.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3pwbA7x6pY59k2dQMwcUhV-d7LJMMYOI',
    appId: '1:83204591815:android:b295b2d4e78bbef91caee2',
    messagingSenderId: '83204591815',
    projectId: 'ecofund-c4310',
    storageBucket: 'ecofund-c4310.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTZsHEow1PRTf-SiHPXl9c55JRpLL30ps',
    appId: '1:83204591815:ios:df1c84486306d6801caee2',
    messagingSenderId: '83204591815',
    projectId: 'ecofund-c4310',
    storageBucket: 'ecofund-c4310.firebasestorage.app',
    iosBundleId: 'com.example.ecofund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTZsHEow1PRTf-SiHPXl9c55JRpLL30ps',
    appId: '1:83204591815:ios:df1c84486306d6801caee2',
    messagingSenderId: '83204591815',
    projectId: 'ecofund-c4310',
    storageBucket: 'ecofund-c4310.firebasestorage.app',
    iosBundleId: 'com.example.ecofund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnzHHUS-J5nYG-czs1xdJhUaKJ-HYvQ7I',
    appId: '1:83204591815:web:6f6ffff9732de9e91caee2',
    messagingSenderId: '83204591815',
    projectId: 'ecofund-c4310',
    authDomain: 'ecofund-c4310.firebaseapp.com',
    storageBucket: 'ecofund-c4310.firebasestorage.app',
  );
}
